### ISSUE TITLE
Variadic inheritence? 

### ISSUE THREAD

**Issue by nitro44x** [Hoshiningen/depixelization#15]
I'm not really sure how to post questions on github... so i made an issue.

Is the following struct variadicly inheriting from its template parameters? 

https://github.com/Hoshiningen/depixelization/blob/48109bcd7d6fbfb3f36bc9b25236e14fcec20048/source/reshaper/source/reshaper/SimilarityGraph.cpp#L9-L13

**Comment by Hoshiningen** [comment]
I'm not sure how to post questions about things on here either, but creating an issue seems like an appropriate way of doing it. It lets you reference lines of code.. seems pretty nifty.

We talked about this earlier, but just to provide some more explanation, I'll also detail it here a bit as well.

You're correct, that struct is an example of variadic inheritance. It's possible to do in since C++11, but I don't think it really becomes useful until C++17, when you can perform the variadic using pack expansions (line 12 in your example).

HeuristicDispatcher is a helper struct that gets instantiated with a variadic pack of lambdas inside a call to `std::visit`:

```c++
std::variant<int, double> someVariant = 2;

std::visit(HeuristicDispatcher{
    [](int value)
    {
         // do something if the variant holds an int
    },
    [](double value)
    {
        // do something if it's actually holding a double...
    }
}, someVariant);
```
When a lambda is compiled and a closure is generated, the closure is given an `operator()` that has the same signature as what was defined for the lambda. When performing the variadic inheritance, `HeuristicDispatcher` is becoming a derived type of each of those lambdas, where each lambda has an `operator()` overload. The call to `using Handlers::operator()...;` is a variadic pack expansion that lifts each of the `operator()` overloads into the member scope of `HeursiticDispatcher`. This allows them to be called directly from an instantiation of that struct, without having to perform a cast to any of the lambda "base" classes.

The next piece of the puzzle is how you actually instantiate an object with a variadic pack of lambdas. There's no constructor that expands the parameter pack, but we're still inheriting from things we're being constructed from. The way this works is with C++17's user-defined template deduction guidelines.

The lines:

```cpp
template<typename... Handlers>
HeuristicDispatcher(Handlers...)->HeuristicDispatcher<Handlers...>;
```

Provide the compiler with the guidelines to properly deduce the types passed into a constructor of that class. I'm not totally sure how this works since I never defined a converting constructor that has a variadic template, but it still enables a correct deduction of the variadic types. It indicates that: "When constructing an object, accept a parameter pack of things. When accepting these things, HeuristicDispatcher should be specialized with the types of those things passed in."

Lastly, when `std::visit` is called, the type inside the supplied variant gets mapped at compile time via overload resolution to one of the `operator()` that were inherited from the supplied lambdas. This is a form of pattern matching in C++, which is pretty exciting.

See https://en.cppreference.com/w/cpp/language/class_template_argument_deduction for more information on user-defined deduction guidelines.
